// Generated by https://quicktype.io

export interface Package {
    id:                number;
    addressstreet:     string;
    addresspostalcode: number;
    clientname:        string;
    packageweight:     string;
    isdelivered:       boolean;
}
